### ISSUE TITLE
怎么让层级深的属性转换到一级属性上来

### ISSUE THREAD

**Issue by ForestHo** [goblin-pitcher/data-adapter#1]
怎么让层级深的属性转换到一级属性上来，也在wh，大佬的微信多少

**Comment by goblin-pitcher** [comment]
刚试了下，深层级的属性移到上一级来，可以这么写
```js
const rules = new Map([
  [['b', 'a'], ['g']]
]);
const obj = {b: {a: 1}};
const transObj = adapter(obj, rules, {retain: false}) // retain为true时会保留obj.b.a的值，默认是false，移动后删除之前的值
```
另外数据适配器不会返回一个新的对象，如果想返回新的对象，最好这么用`adapter(deepClone(obj), rules)`，这么设计是因为数据适配器一般用于接口返回的数据，之前公司业务场景中后端返回数据可能很大，虽然转换的过程复杂度也就是O(n)，不过基于性能和场景考虑，还是没有在适配器内部加deepClone方法，有相关需求可以在外部封一层。

这个项目是之前为了应付组内分享临时搞的，写的比较粗糙...
——————————————————————
我微信 799343190，有空一起学习交流😀

**Comment by ForestHo** [comment]
> 

深层的属性移到一级，配置多个规则没有全部生效，只生效了一个

**Comment by goblin-pitcher** [comment]
已修复
